spring:
  config:
    import: configserver:https://ms-innovatube-config-server-uxqd.onrender.com/
  application:
    name: innovatube-usuarios

server:
  port: 8093

  eureka:
    instance:
      prefer-ip-address: true
